runtime: java
env: standard

handlers:
- url: /.*
  script: auto

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
