name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud config set account $(gcloud config get-value account)

    - name: Set version
      id: vars
      run: echo "VERSION=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet --version=$VERSION --no-promote
