name: Build and Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Android SDK and Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
        sudo unzip commandlinetools.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
        sudo chmod -R 777 /usr/local/lib/android/sdk
        yes | sudo /usr/local/lib/android/sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk --licenses
        sudo /usr/local/lib/android/sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=/usr/local/lib/android/sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Set up local.properties
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > $GITHUB_WORKSPACE/android/local.properties

    - name: Grant execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean assemble -x test --build-cache --quiet

    - name: Upload build artifacts to GCS
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gsutil cp android/app/build/outputs/apk/release/app-release.apk gs://libgdx_game/builds/app-release-$(date +%Y%m%d%H%M%S).apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts from GCS
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gsutil cp $(gsutil ls gs://libgdx_game/builds | sort | tail -n 1) .

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --project=${{ secrets.GCP_PROJECT_ID }} --quiet
