name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Use custom Docker image with Android SDK
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          dockerdockie/android-sdk:custom \
          /bin/bash -c "\
            chmod +x ./gradlew && \
            echo 'sdk.dir=/usr/local/lib/android/sdk' > android/local.properties && \
            ./gradlew clean assemble -x test --build-cache --quiet && \
            chmod -R a+r /workspace/android/build && \
            cat android/local.properties && \
            cat /workspace/android/local.properties"

    - name: Create local.properties file for Cloud Build
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > android/local.properties

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml
        promote: true

      run: |
        gcloud app deploy app.yaml --quiet --version=$VERSION --no-promote --verbosity=debug