name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup GCloud Auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: '30'
        build-tools: '30.0.3'
        ndk: '21.4.7075529'

    - name: Create local.properties file
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > android/local.properties

    - name: Set version
      id: vars
      run: echo "VERSION=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet --version=$VERSION --no-promote
