name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup GCloud Auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: '30'
        build-tools: '30.0.3'
        ndk: '21.4.7075529'

    - name: Create necessary directories in deploy
      run: |
        mkdir -p deploy/android
        mkdir -p deploy/core
        mkdir -p deploy/desktop
        mkdir -p deploy/html
        mkdir -p deploy/gradle/wrapper

    - name: Copy necessary files to deploy directory
      run: |
        cp -r android/* deploy/android/
        cp -r core/* deploy/core/
        cp -r desktop/* deploy/desktop/
        cp -r html/* deploy/html/
        cp build.gradle deploy/
        cp gradle.properties deploy/
        cp gradlew deploy/
        cp gradlew.bat deploy/
        cp settings.gradle deploy/
        cp README.md deploy/
        cp gradle/wrapper/gradle-wrapper.jar deploy/gradle/wrapper/
        cp gradle/wrapper/gradle-wrapper.properties deploy/gradle/wrapper/

    - name: Create .gcloudignore file
      run: |
        echo '*' > deploy/.gcloudignore
        echo '!app.yaml' >> deploy/.gcloudignore
        echo '!android/' >> deploy/.gcloudignore
        echo '!core/' >> deploy/.gcloudignore
        echo '!desktop/' >> deploy/.gcloudignore
        echo '!html/' >> deploy/.gcloudignore
        echo '!build.gradle' >> deploy/.gcloudignore
        echo '!gradle.properties' >> deploy/.gcloudignore
        echo '!gradlew' >> deploy/.gcloudignore
        echo '!gradlew.bat' >> deploy/.gcloudignore
        echo '!settings.gradle' >> deploy/.gcloudignore
        echo '!README.md' >> deploy/.gcloudignore
        echo '!gradle/wrapper/gradle-wrapper.jar' >> deploy/.gcloudignore
        echo '!gradle/wrapper/gradle-wrapper.properties' >> deploy/.gcloudignore

    - name: Create local.properties file
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > deploy/android/local.properties

    - name: Set version
      id: vars
      run: echo "VERSION=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Deploy to App Engine
      run: |
        gcloud app deploy deploy/app.yaml --quiet --version=$VERSION --no-promote
