name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'
        export_default_credentials: true

    - name: Install Android SDK and Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
        sudo unzip commandlinetools.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
        yes | sudo /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
    
    - name: Verify SDK installation
      run: |
        echo "Listing contents of /usr/local/lib/android/sdk:"
        ls -al /usr/local/lib/android/sdk
        echo "Listing contents of /usr/local/lib/android/sdk/cmdline-tools:"
        ls -al /usr/local/lib/android/sdk/cmdline-tools
        echo "Listing contents of /usr/local/lib/android/sdk/cmdline-tools/latest:"
        ls -al /usr/local/lib/android/sdk/cmdline-tools/latest

    - name: Create local.properties file
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > ${{ github.workspace }}/local.properties

    - name: Verify local.properties file
      run: cat ${{ github.workspace }}/local.properties

    - name: Export ANDROID_SDK_ROOT
      run: |
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_ENV

    - name: Print environment variables
      run: |
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"

    - name: Sleep to ensure environment is set
      run: sleep 10

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml
        promote: true
